import express from 'express'; import http from 'http'; import {Server} from 'socket.io'; import crypto from 'crypto';
const app=express(), server=http.createServer(app), io=new Server(server), rooms=new Map(), PORT=process.env.PORT||10000;
app.use(express.static('public'));
const R=['A','2','3','4','5','6','7','8','9','10','J','Q','K'], S=['♠','♥','♦','♣'];
const code=()=>{let c;do c=crypto.randomBytes(3).toString('hex').toUpperCase();while(rooms.has(c));return c};
const deck=()=>S.flatMap(s=>R.map(r=>({id:crypto.randomUUID(),r,s}))).sort(()=>Math.random()-.5);
function next(room,i){for(let n=1;n<=room.players.length;n++){let x=(i+n)%room.players.length;if(room.players[x]?.hand.length)return x}return -1}
function sets(p){let out=[];for(const r of R)if(p.hand.filter(c=>c.r===r).length===4){p.hand=p.hand.filter(c=>c.r!==r);p.removed+=4;out.push(r)}return out}
function state(room,sid){let p=room.players.find(x=>x.id===sid);return {code:room.code,host:room.host,started:room.started,phase:room.phase,current:room.current,targetRank:room.targetRank,declaration:room.declaration&&{player:room.declaration.player,count:room.declaration.count,rank:room.declaration.rank},pileCount:room.pile.length,players:room.players.map(x=>({id:x.id,name:x.name,handCount:x.hand.length,removed:x.removed})),me:p&&{id:p.id,name:p.name,hand:p.hand},winner:room.winner,reveal:room.reveal,message:room.message}}
function send(room){room.players.forEach(p=>io.to(p.id).emit('state',state(room,p.id)))}
function start(room){let d=deck();room.players.forEach(p=>{p.hand=[];p.removed=0});d.forEach((c,i)=>room.players[i%room.players.length].hand.push(c));room.current=Math.floor(Math.random()*room.players.length);room.started=true;room.phase='play';room.pile=[];room.targetRank=null;room.declaration=null;room.winner=null;room.reveal=null;room.players.forEach(sets);room.message=`${room.players[room.current].name} is the first player.`;send(room)}
function throwCards(room,sid,ids,rank){let i=room.players.findIndex(p=>p.id===sid);if(i<0||i!==room.current||room.phase!=='play')return;let p=room.players[i];room.reveal=null;if(!Array.isArray(ids)||!ids.length||ids.length>p.hand.length)return;if(room.targetRank&&rank!==room.targetRank)return;let chosen=p.hand.filter(c=>ids.includes(c.id));if(chosen.length!==ids.length)return;p.hand=p.hand.filter(c=>!ids.includes(c.id));room.pile.push(...chosen);room.declaration={player:i,count:chosen.length,rank,actual:chosen.every(c=>c.r===rank)};room.targetRank=rank;if(!p.hand.length){room.winner=p.name;room.phase='gameover';room.message=`${p.name} emptied their hand and wins!`;send(room);return}room.current=next(room,i);room.phase='challenge';room.message=`${p.name} declared ${chosen.length} × ${rank}. ${room.players[room.current].name}, choose TRUTH or LIE.`;send(room)}
function challenge(room,sid,truth){let ch=room.players.findIndex(p=>p.id===sid);if(ch!==room.current||room.phase!=='challenge'||!room.declaration)return;let d=room.declaration;if(truth){room.phase='play';room.current=ch;room.message=`${room.players[ch].name} accepted the claim. Use the same rank: ${d.rank}.`;send(room);return}let cards=room.pile.splice(0), dec=d.player, actual=d.actual;room.reveal={result:actual?'TRUTH':'LIE',cards:cards.map(c=>({id:c.id,r:c.r,s:c.s}))};if(actual){room.players[ch].hand.push(...cards);room.current=dec}else{room.players[dec].hand.push(...cards);room.current=ch}let notes=[];room.players.forEach(p=>sets(p).forEach(r=>notes.push(`${p.name} completed four ${r}s`)));if(!room.players[room.current].hand.length){room.winner=room.players[room.current].name;room.phase='gameover'}else room.phase='play';room.message=actual?`TRUTH! ${room.players[dec].name} was telling the truth. ${room.players[ch].name} takes the pile; turn returns to ${room.players[dec].name}.`:`LIE! ${room.players[dec].name} was lying. ${room.players[dec].name} takes the pile; ${room.players[ch].name} starts.`;if(notes.length)room.message+=' '+notes.join('. ')+'.';room.declaration=null;room.targetRank=null;send(room)}
io.on('connection',socket=>{socket.on('createRoom',({name},cb)=>{name=String(name||'Player').trim().slice(0,20);let c=code(),room={code:c,host:socket.id,players:[],started:false,phase:'lobby',current:0,targetRank:null,pile:[],declaration:null,winner:null,message:'Waiting for players...',reveal:null};rooms.set(c,room);room.players.push({id:socket.id,name,hand:[],removed:0});socket.join(c);cb({ok:true,code:c});send(room)});socket.on('joinRoom',({code:c,name},cb)=>{c=String(c||'').trim().toUpperCase();name=String(name||'Player').trim().slice(0,20);let room=rooms.get(c);if(!room)return cb({ok:false,error:'Room not found.'});if(room.started)return cb({ok:false,error:'Game already started.'});if(room.players.length>=10)return cb({ok:false,error:'Room is full.'});if(room.players.some(p=>p.name.toLowerCase()===name.toLowerCase()))return cb({ok:false,error:'That name is already in use.'});room.players.push({id:socket.id,name,hand:[],removed:0});socket.join(c);room.message=`${name} joined the room.`;cb({ok:true,code:c});send(room)});socket.on('startGame',({code:c})=>{let room=rooms.get(c);if(room&&room.host===socket.id&&room.players.length>=2)start(room)});socket.on('throwCards',({code:c,ids,rank})=>{let room=rooms.get(c);if(room)throwCards(room,socket.id,ids,rank)});socket.on('challenge',({code:c,truth})=>{let room=rooms.get(c);if(room)challenge(room,socket.id,!!truth)});socket.on('disconnect',()=>{for(const [c,room] of rooms){let i=room.players.findIndex(p=>p.id===socket.id);if(i<0)continue;let name=room.players[i].name,was=i===room.current;room.players.splice(i,1);if(!room.players.length){rooms.delete(c);continue}if(room.host===socket.id)room.host=room.players[0].id;if(room.started&&room.players.length<2){room.started=false;room.phase='lobby';room.pile=[];room.declaration=null;room.targetRank=null;room.reveal=null}else if(room.started&&was)room.current=i%room.players.length;else if(room.started&&i<room.current)room.current--;room.message=`${name} left the room.`;send(room)}}})
server.listen(PORT,'0.0.0.0',()=>console.log(`Bakakay Online on ${PORT}`));
